### ISSUE TITLE
deferRequestBy option

### ISSUE THREAD

**Issue by AndreySukhov** [nobbynobbs/react-dadata-suggestions#13]
Hello!

Is it possible to configure deferRequestBy option? As in https://confluence.hflabs.ru/pages/viewpage.action?pageId=207454318 jquery plugin

**Comment by nobbynobbs** [comment]
Hi. No, `deferRequestBy` option is not supported. It's tricky to implement such feature with promises, at least for me, I'm not a JS-developer )

**Comment by sinxwal** [comment]
@nobbynobbs please, take a look at #14

**Comment by nobbynobbs** [comment]
@sinxwal, thank you! 

@AndreySukhov check for v1.0.0, component supports deferRequestBy option now.
