### ISSUE TITLE
Suggestions cannot be selected on iphone

### ISSUE THREAD

**Issue by SDKiller** [nobbynobbs/react-dadata-suggestions#15]
I was told that suggestions list is not "selectable" on iphones (at least on SE and 6).
It is opened, but not "cliсkable" - nothing is selected, list remains open.

On android and desktop (windows) everything is ok. Not tested on Mac yet.

I asked the same users to compare with original dadata jquery suggestions - they say everything is ok there.

Could you please investigate this issue?

**Comment by SDKiller** [comment]
They say there is the same issue on iphone with your example on https://codesandbox.io/s/p95804280q

**Comment by nobbynobbs** [comment]
I haven't apple devices for test, but I think I know what the issue. I'll try fix it at the evening.

**Comment by SDKiller** [comment]
Thanks.

I have several users to test on )

**Comment by SDKiller** [comment]
BTW, a came across this fork 

https://github.com/moonrtv/react-dadata-suggestions/commit/7ad3cfe0633bec2c7b681bbd2b4e293e436fae3c

Maybe it's related?

**Comment by nobbynobbs** [comment]
> Maybe it's related?

Yes, probably it's related, but internet says it's dirty hack and can produce strange behavior.

**Comment by SDKiller** [comment]
https://github.com/facebook/react/issues/7122

**Comment by nobbynobbs** [comment]
@SDKiller please, try to install version 1.0.1

**Comment by SDKiller** [comment]
Did you mean that hack?

https://stackoverflow.com/questions/10577906/how-to-make-my-click-function-work-with-ios

Ok, I'll try and give you feedback as soon as someone of my apple users will be online (probably not today).
Thanks

**Comment by SDKiller** [comment]
Works on SE :+1: 
Tomorrow I'll receive more feedback about other models.

**Comment by nobbynobbs** [comment]
@SDKiller 
Could you give me some feedback please? Is everything fine on iOS devices?

**Comment by SDKiller** [comment]
Hi, I still have no feedback from other users, only the one with iphone SE
- its ok.
Probably you may close issue - I'll come back if case I receive any
additional info.

пт, 22 мар. 2019 г., 14:25 Roman <notifications@github.com>:
