### ISSUE TITLE
Ошибка после unmount компонента из-за активного запроса саджестов 

### ISSUE THREAD

**Issue by Volosojui** [nobbynobbs/react-dadata-suggestions#16]
Похоже возникает из-за обновления состояния компонента в ответе реквеста, когда самого компонента уже нет.

**Comment by nobbynobbs** [comment]
Привет. Если есть идеи как пофиксить, я с радостью приму пул-реквест, потому что я напрочь забыл реакт, что там за life-cycle и вот это вот все.

**Comment by Volosojui** [comment]
Лови https://github.com/nobbynobbs/react-dadata-suggestions/pull/17
