### ISSUE TITLE
Возможность отключить suggestions

### ISSUE THREAD

**Issue by Volosojui** [nobbynobbs/react-dadata-suggestions#18]
На проекте упёрлись в то, что для некоторых регионов нам не нужны подсказки и, соответственно, запрос к dadata. Попробовали подменить на другой инпут, но тогда слетает каретка (задача отключить подсказки в момент редактирования адреса).

Можем ли мы добавить опцию `disableDadata`, чтобы отключить подсказки и запрос к dadata при редактировании?

**Comment by nobbynobbs** [comment]
Если не поломаете обратную совместимость, то пожалуйста, почему нет.
