### ISSUE TITLE
Не работают touch ивенты 

### ISSUE THREAD

**Issue by GoAndrew** [nobbynobbs/react-dadata-suggestions#19]
На мобильных устройствах невозможно выбрать значения, которые показываются в всплывающем окне подсказок. Как можно решить данную проблему?

**Comment by nobbynobbs** [comment]
@GoAndrew, напиши пожалуйста почему закрыто, как решилось. Вдруг кому-то будет полезно.

Похожее ишью: #15

**Comment by GoAndrew** [comment]
@nobbynobbs Просто не обратил внимания, что вышла новая версия. Обновил – все заработало :)
