### ISSUE TITLE
Why `dist` directory is not in repo?

### ISSUE THREAD

**Issue by tilvan** [nobbynobbs/react-dadata-suggestions#20]
I tried to import package into my project but module was not found.
By the way, `main` from `package.json` is related to `dist/index.js`

**Comment by nobbynobbs** [comment]
I just can't imagine react project without build stage :man_shrugging:

**Comment by nobbynobbs** [comment]
Probably I should change package.json a bit. I'll try it on weekend.

- [stackoverflow](https://stackoverflow.com/questions/31642477/how-to-publish-a-npm-package-with-distribution-files)

**Comment by nobbynobbs** [comment]
I've published v.1.0.3 just now, it contains dist folder.
