### ISSUE TITLE
Using react-dadata-suggestions with Formik or react-final-form

### ISSUE THREAD

**Issue by svetlanapuro** [nobbynobbs/react-dadata-suggestions#23]
Hi there,

Do you have an example of using `react-dadata-suggestions` with Formik or Final Form? I tried to do it myself with Final Form, but I can't get it to work. Here is my [codesandbox](https://codesandbox.io/s/react-final-form-wreact-input-mask-7sy32?fontsize=14).

Here is a [codesandbox](https://codesandbox.io/s/dadata-test-wformik-not-working-8sw24?fontsize=14) for Formik, which is also not working.

**Comment by nobbynobbs** [comment]
Hello.

I think for Final Form you could use the `mutators` for passing values from react-dadata-suggestion event handler into final form's state. Here is an [example](https://codesandbox.io/embed/react-final-form-wdadata-not-working-kni3d)

**Comment by svetlanapuro** [comment]
Thank you very much for your reply! Yes, it works, but the input itself is cleared now.

**Comment by nobbynobbs** [comment]
Yes it's empty. You should somehow pass the value into the `query` attribute of Suggestions component. Sorry, I'm not familiar with Final Forms, so I can't help.
Also, I've just noticed the deprecation warning about mutators in my previous example, you should use `form: mutators` instead of `mutators`.

**Comment by nobbynobbs** [comment]
@iloveip 
Looks like it [works](https://codesandbox.io/embed/react-final-form-wdadata-kni3d)
Also I fix deprecation warning.

**Comment by svetlanapuro** [comment]
Thank you very much 🙏

**Comment by svetlanapuro** [comment]
Hi there,

I've just noticed, that if you select an address (for example, with street), and then want to add a house, the input is cleared as soon as you start typing. (If you do the same with arrows up and down in the first place, everything is ok.) Is there any way to fix it?

**Comment by nobbynobbs** [comment]
try

```
onChange={(event, value) => props.input.onChange({value: event})}
```

**Comment by svetlanapuro** [comment]
Yes, now it works, thank you very much!

**Comment by svetlanapuro** [comment]
I'm sorry, but I have one more question 🙏

In my [example](https://codesandbox.io/s/react-final-form-wdadata-uksb7?fontsize=14) the suggestions list hides and shows on every key press as I type. Is there anyway to fix it?

**Comment by nobbynobbs** [comment]
I doubt if it's possible in current implementation.

How it works: `onChange` event handler set the new value for form field, then this value passed into `query` prop of dadata component, and this causes `componentWillReceiveProps` handler fired, which clears suggestions list.

I'll think how to improve this use-case.

**Comment by svetlanapuro** [comment]
Ok, thank you very much.

**Comment by svetlanapuro** [comment]
Hi there,

Do you have any update on this?

**Comment by nobbynobbs** [comment]
So-so. I know how to fix your issue, but I don't know how to preserve current behavior for other cases.

**Comment by svetlanapuro** [comment]
Could you please share your solution? Maybe I can fork your repository and fix it only for me (if other users don't have such problem).

**Comment by nobbynobbs** [comment]
something like this

```patch
diff --git a/src/index.js b/src/index.js
index a8f8b50..9d2f3e6 100644
--- a/src/index.js
+++ b/src/index.js
@@ -74,12 +74,11 @@ class DadataSuggestions extends Component {
   }
 
   componentWillReceiveProps(nextProps) {
-    this.setState({
-      query: nextProps.query,
-      suggestions: [],
-      showSuggestions: false,
-      success: false,
-    });
+    const newQuery = nextProps.query;
+    const { query } = this.props;
+    if (newQuery != query) {
+      this.handleChange(newQuery);
+    }
   }
 
   componentWillUnmount() {
@@ -126,8 +125,7 @@ class DadataSuggestions extends Component {
     return searchWords;
   };
 
-  handleChange = (e) => {
-    const query = e.target.value;
+  handleChange = (query) => {
     const { deferRequestBy } = this.props;
 
     this.clearFetchTimeout();
@@ -258,7 +256,7 @@ class DadataSuggestions extends Component {
     return (
       <div className="suggestions-container">
         <QueryInput
-          onChange={ this.handleChange }
+          onChange={ e => this.handleChange(e.target.value) }
           placeholder={ this.props.placeholder }
           loading={ loading }
           query={ query }
```

**Comment by nobbynobbs** [comment]
I've merged #25, please check release v1.1.0.

Just add new prop `receivePropsBehaveLikeOnChange={true}` to dadata component in your code. There is [example](https://codesandbox.io/embed/react-final-form-wreact-dadata-suggestions-b01kt) based on your last link from codesandbox.

Looks like it works.

upd. :laughing: :rofl: no, it still doesn't work. Now select event is broken :thinking:

**Comment by svetlanapuro** [comment]
Ok. So I just wait? Or I can go ahead and fix you repo as you said above?

**Comment by nobbynobbs** [comment]
@iloveip check v1.1.1 please, I hope it works. Link is the same as [previous](https://codesandbox.io/embed/react-final-form-wreact-dadata-suggestions-b01kt)

**Comment by svetlanapuro** [comment]
😃Thank you very much!  Everything works great now!
