### ISSUE TITLE
Add a class name to the query input

### ISSUE THREAD

**Issue by svetlanapuro** [nobbynobbs/react-dadata-suggestions#24]
Is there any way to change a class name for the input? May be add it as a prop?

**Comment by nobbynobbs** [comment]
No, don't want to do it.

**Comment by svetlanapuro** [comment]
So the only way is to add styles to the class, which is already there (`suggest-input`)?

**Comment by nobbynobbs** [comment]
Yes, you can override existing classes.

**Comment by svetlanapuro** [comment]
Ok, thank you very much.
