### ISSUE TITLE
How to add styles for suggestion highlighting

### ISSUE THREAD

**Issue by svetlanapuro** [nobbynobbs/react-dadata-suggestions#29]
Hello,

How can I add css styles for highlighted words? I can't find corresponding class in [styles](https://github.com/nobbynobbs/react-dadata-suggestions/blob/master/src/styles/styles.less).

**Comment by nobbynobbs** [comment]
There wasn't supporting for highlight customizing...
But there is now. Update version to 1.2.1 and use `.suggestions-highlighting` class.

**Comment by svetlanapuro** [comment]
Thank you for such quick reply 🙏

**Comment by svetlanapuro** [comment]
Does highlighting work only with the first line? I tried it with parties and the numbers in `suggestions-subtext` are not being highlighted.

**Comment by nobbynobbs** [comment]
Yes, highlighting works for main text content only.
