### ISSUE TITLE
Styles for LIQUIDATED are not working

### ISSUE THREAD

**Issue by svetlanapuro** [nobbynobbs/react-dadata-suggestions#30]
Hello,

Styles for LIQUIDATED companies are not working in react-final-form. Is there any way to fix it?

Here is [codesandbox](https://codesandbox.io/embed/react-final-form-wreact-dadata-suggestions-uksb7?fontsize=14) (you can try it with `ИНН 110380625809`).

**Comment by nobbynobbs** [comment]
Sorry, I don't understand the issue.
I can't see any processing for organization state value in your code example.

**Comment by svetlanapuro** [comment]
If you type in `ИНН 110380625809` you will see two suggestions. One of them is active and another one is liquidated. The liquidated one should be strikethrough as in image below. There are even [styles](https://github.com/nobbynobbs/react-dadata-suggestions/blob/4142bd64f71a15f5184707fb42e50489e36d8d0c/src/styles/styles.less#L216) for this in your library, but they are not being applied. 

<img width="1312" alt="Снимок экрана 2019-09-19 в 20 25 22" src="https://user-images.githubusercontent.com/4873895/65266512-e4c18b00-db1b-11e9-9fb5-6e3467e8d8cb.png">

**Comment by nobbynobbs** [comment]
This component it much more simpler comparing to official dadata jQuery-plugin. I'd used theirs DOM-structure and styles, but implemented only base functional, not all the bells and whistles it has.

**Comment by nobbynobbs** [comment]
Updated in v1.2.2

**Comment by svetlanapuro** [comment]
Thank you very much) I think it will be the best library for dadata suggestions 😍
