### ISSUE TITLE
Initializing react-dadata-suggestions with data from the state

### ISSUE THREAD

**Issue by svetlanapuro** [nobbynobbs/react-dadata-suggestions#32]
Hi there,

I have one more question about using `react-dadata-suggestions` with `react-final-form`.

I would like to initialize the form with some data from the state. When I do it, all the fields are working, except the input with `react-dadata-suggestions`. Here is an [example](https://codesandbox.io/s/react-final-form-wreact-dadata-suggestions-initialized-9ufhm?fontsize=14).

Is there any way I can fix it?

**Comment by svetlanapuro** [comment]
I guess, it has something to do with the `query`.  I can see in React DevTools that it has been set, but in the input itself it's not displayed.

**Comment by nobbynobbs** [comment]
Probably it's problem with component will receive props lifecycle hook. I'll look at it later

**Comment by nobbynobbs** [comment]
I found a couple of bugs in you example, first you don't pass the query props from redefined component into original, and second, I doubt if it's necessary to pass the input's props into Dadata component. If you [fix it](https://codesandbox.io/embed/react-final-form-wreact-dadata-suggestions-initialized-eu90m), things looks a bit better, but still doesn't works as you expected and I don't know if I can fix it. Component made for fetching data from api, and not taking them from external state. Strange use cases, strange problems.

**Comment by svetlanapuro** [comment]
Thank you very much. My use case is as follows. We are making a new service similar to this one https://www.iloveip.ru/usn/. A user fills in a form to download a document. Then he is redirected to another page for payment and after the payment he is redirected back to the original page actually to download the document. When he is redirected, the form has to be completed with the data, he has already submitted. This is when we need to initialize the form with the data from the state (which we fetch by API from our server).

**Comment by svetlanapuro** [comment]
Скажите, пожалуйста, сможете ли вы помочь на платной основе? Если да, не могли бы вы написать мне в Telegram [@smalakhova](https://tele.click/smalakhova).

**Comment by nobbynobbs** [comment]
I'll see it for free. But I can't see quick solution for this use-case right now.

**Comment by svetlanapuro** [comment]
Ok, thank you very much.

**Comment by svetlanapuro** [comment]
Hi there,

Do you have any updates on this?

**Comment by nobbynobbs** [comment]
No. I've spent enough of time looking on this issue, but I still don't understand how the desired behavior could be achieved in the proper way. Maybe you could just display the data in another component after the redirect?

**Comment by svetlanapuro** [comment]
Unfortunately, we can't use another component, as the client can download several documents with different data. So we need to keep the dadata component active.

But I've checked it once again and I guess I don't need to use `query={values["party"] && values["party"].value}` anymore. (Maybe it's due to `receivePropsBehaveLikeOnChange={true}`.) So now I can set query as `query={this.state.data.party.value}`. The only problem is that if the query is present it immediately starts to [fetch suggestions](https://codesandbox.io/s/react-final-form-wreact-dadata-suggestions-initialized-9ufhm?fontsize=14). Maybe you could make it an option? Similar to autoload option [here](https://github.com/vitalybaev/react-dadata#%D1%81%D0%B2%D0%BE%D0%B9%D1%81%D1%82%D0%B2%D0%B0).

**Comment by nobbynobbs** [comment]
> Maybe you could make it an option? Similar to autoload option here.

I doubt it'll do the trick, autoload option on the link works for didMount hook and it's pretty simple, but here we must handle willReceiveProps somehow instead

**Comment by svetlanapuro** [comment]
Maybe you can do autoload `true` by default? And if it's `false`, add to `handleChange`? I guess that's what's causing the suggestions list to show on load.

**Comment by nobbynobbs** [comment]
Could you check [this](https://codesandbox.io/embed/react-final-form-wreact-dadata-suggestions-initialized-eu90m) with all you use-cases please.

**Comment by svetlanapuro** [comment]
Looks like it works 😍

P.S. Do I need to change `onChange`? It looks like it also works with `onChange={event => input.onChange({ value: event })}`

**Comment by nobbynobbs** [comment]
> P.S. Do I need to change onChange? It looks like it also works with onChange={event => input.onChange({ value: event })}

What do you mean? Can you remove console.log from handler? Sure you can.

**Comment by svetlanapuro** [comment]
> > P.S. Do I need to change onChange? It looks like it also works with onChange={event => input.onChange({ value: event })}
> 
> What do you mean? Can you remove console.log from handler? Sure you can.

No, I mean can I use `onChange={event => input.onChange({ value: event })}` instead of `onChange={query => input.onChange({ value: query })}` as in your last example? It also seems to work.

**Comment by svetlanapuro** [comment]
Also how can I update to beta version? If I run `npm update` I get only version `1.2.2`.

**Comment by nobbynobbs** [comment]
> how can I update to beta version?

Well... I don't know. I've published v1.3.0 

> No, I mean can I use onChange={event => input.onChange({ value: event })} instead of onChange={query => input.onChange({ value: query })} as in your last example? It also seems to work.

It's just an argument name, you could use anything you want.

**Comment by svetlanapuro** [comment]
Thank you very much. I have upgraded to v 1.3.0 and it seems to be working now except one more thing. Is it possible that the input stays in focus after the value has been cleared? I have a validation set up, which shows an error message, after the field loses focus (is not [active](https://final-form.org/docs/react-final-form/types/FieldRenderProps#metaactive) anymore). But now this validation doesn't work, and I can see the error message only when I hit submit. Here is an [example](https://codesandbox.io/s/react-final-form-wreact-dadata-suggestions-initialized-y1pi6?fontsize=14).

**Comment by svetlanapuro** [comment]
I've added `fieldsState` to the example above. You can see that `meta.active` doesn't work at all, even if the input is focused. That's why the validation doesn't work, as it's subscribed to its changes.

**Comment by nobbynobbs** [comment]
In your DadataAddress.jsx file pass the props from `input` (final forms Field) into dadata component like

```
onBlur={input.onBlur}
onFocus={input.onFocus}
```

You can't use object destructuring like this
```
{...input}
```
it doesn't work for some reason, so you should take care about passing the necessary props by yourself.

**Comment by svetlanapuro** [comment]
Thank you very much! That solved the problem partly. I still have one more question. If I delete the value from the input, the value for the field stays filled in with an empty string like this:

```
"party": {
    "value": ""
  }
```

So now my classnames don't work, which depend on `input.value`. Is there any way to fix it?

**Comment by nobbynobbs** [comment]
I can't see such part of the state.
If you mean this

```json
"party": {
    "input": {
      "name": "party",
      "value": {
        "value": ""
      }
    }
```

and want behavior for empty input like this

```json
"email": {
    "input": {
      "name": "email",
      "value": ""
    }
```

you could use onChange like this:
```javascript
onChange={query => !!query ? input.onChange({ value: query }) : input.onChange("")}
```

**Comment by svetlanapuro** [comment]
Everything is working now. Thank you very much for your help!
