### ISSUE TITLE
Выпадалка в body

### ISSUE THREAD

**Issue by victornikitin** [nobbynobbs/react-dadata-suggestions#34]
Выпадалка с подходящими вариантами сейчас размещается в том же контейнере. Это не всегда удобно, если родительские элементы имеют ограничение по overflow.

Планируется ли возможность размещения выпадалки в body и абсолютное позиционирование ее относительно инпута?

Или как сейчас решить эту проблему?

**Comment by nobbynobbs** [comment]
Привет. Менять структуру элементов не планируется, как решить проблему с overflow тоже не знаю.

**Comment by gusssar** [comment]
@victornikitin но вы можете сами поменять структуру самостоятельно импортом 'styles.css':
```
.suggestions-container {
  position: relative;
}

.suggestions-wrapper {
  position: absolute;
  z-index: 99;
  top: 38px; // высота инпута
  left: 0;
}
```
