### ISSUE TITLE
Возможность указать приоритет города

### ISSUE THREAD

**Issue by svetlanapuro** [nobbynobbs/react-dadata-suggestions#35]
Добрый день.

Скажите, пожалуйста, есть ли в библиотеке возможность указать [приоритет города при ранжировании](https://confluence.hflabs.ru/pages/viewpage.action?pageId=285343795) (`locations_boost`)? Я попробовала указать приоритет в поле `specialRequestOptions`, но мне кажется, что он не срабатывает. Вот ссылка на [codesandbox](https://codesandbox.io/s/react-dadata-suggestions-components-7r5kx?fontsize=14).

**Comment by nobbynobbs** [comment]
Добрый. По-умолчанию приоритет определяется автоматически в соответствии с местоположением пользователя. Чтобы указать locations_boost вручную в компонент нужно дополнительно передать пропс
```
geolocation={false}
```

**Comment by svetlanapuro** [comment]
Ок. Большое спасибо!
