### ISSUE TITLE
Возможность передать input дополнительные параметры

### ISSUE THREAD

**Issue by svetlanapuro** [nobbynobbs/react-dadata-suggestions#36]
Добрый день.

Скажите, пожалуйста, можно ли передать `input` дополнительные параметры, например,
`tabIndex="0" data-select data-name={input.name}`?

**Comment by nobbynobbs** [comment]
Здравствуйте.

Если я правильно понял вопрос и пропсы нужно поднять непосредственно во вложенный в компонент input, то нет, сейчас так не работает, туда пробрасываются только некоторые пропсы из родительского компонента.

**Comment by svetlanapuro** [comment]
Скажите, пожалуйста, а можно ли как-то передать фокус для input?

Мы используем библиотеку `final-form-focus`, которая передаёт фокус первому полю с ошибкой при попытке отправить форму. Здесь можно посмотреть пример [https://codesandbox.io/s/focus-on-error-wreact-dadata-suggestions-test-7isln?fontsize=14](https://codesandbox.io/s/focus-on-error-wreact-dadata-suggestions-test-7isln?fontsize=14).

Там три вида инпутов: обычное поле (Number), компонент `react-select` и компонент `react-dadata-suggestions`. Обычное поле сразу получает фокус, компонент `react-select` через реф. А в компоненте `react-dadata-suggestions` получается передать фокус только внешнему div.

**Comment by svetlanapuro** [comment]
Добрый день. Скажите, пожалуйста, есть ли у вас какая-то информация по этому вопросу?

**Comment by nobbynobbs** [comment]
см. v1.3.1
[песочница](https://codesandbox.io/s/focus-on-error-wreact-dadata-suggestions-test-no0sm)

Добавил возможность передать в компонент пропс `name`, он пробросится прямо в `input`, и в таком варианте react-form-focus работает из коробки, в смысле со стандартным декоратором.

Пробовал пробрасывать в `input` все ненужные самому компоненту пропсы, но так совсем не работает, туда пробрасывается много всего лишнего.

**Comment by svetlanapuro** [comment]
Вроде всё отлично! `name` достаточно, большое спасибо!

**Comment by svetlanapuro** [comment]
Добрый день.

Не могли бы вы ещё добавить для `input` `autocomplete="off"`? Раньше автозаполнения вроде не было, а сейчас появилось(

**Comment by nobbynobbs** [comment]
добавил, скачайте 1.3.2
это видимо какие-то приколы от html5, скорее всего автокомплит для безымянных инпутов не работает, поэтому раньше не было )

**Comment by svetlanapuro** [comment]
Да, теперь всё ок) Большое спасибо!

**Comment by nobbynobbs** [comment]
@iloveip обновите пожалуйста библиотеку, там небольшой фикс
см #38

**Comment by svetlanapuro** [comment]
Ок, большое спасибо)
