### ISSUE TITLE
Как передать атрибут id компоненту

### ISSUE THREAD

**Issue by ghost** [nobbynobbs/react-dadata-suggestions#39]
Как передать атрибут id компоненту?
```js
<DadataSuggestions
            {...input}
            token="***"
            placeholder="Введите город"
            id= "Тест"
         />
```

**Comment by nobbynobbs** [comment]
Ну вот как вы написали, так и передать, он останется в пропсах компонента. Но в то, что отрендерится в DOM id не пробрасывается.

**Comment by ghost** [comment]
В таком случае, как пробросить в DOM?

**Comment by nobbynobbs** [comment]
Никак. А зачем?
