### ISSUE TITLE
`bounds` prop

### ISSUE THREAD

**Issue by tilvan** [nobbynobbs/react-dadata-suggestions#42]
Is it possible to use `bounds` param for address suggestions?
Like here:
- https://dadata.userecho.com/communities/1/topics/462-v-bounds-peredavat-2-i-bolshe-parametrov
- https://codepen.io/dadata/pen/cGkah?editors=101

@nobbynobbs

**Comment by nobbynobbs** [comment]
No, `bounds` support is not implemented, but you could customize request body using `specialRequestOptions` property. Just add all you need in this props and it will be merged into request body. For `bounds` it looks like this:

```js
specialRequestOptions = {{
  from_bound: { value: "region" },
  to_bound: { value: "area" }
}}
```

**Comment by tilvan** [comment]
@nobbynobbs thx
