### ISSUE TITLE
Как связать эту библиотеку с useForm?

### ISSUE THREAD

**Issue by HeisPovedim** [nobbynobbs/react-dadata-suggestions#58]
Здравствуйте, я использую поле для ввода email адреса, но проблема в том что email у меня находится в форме, как и все остальное. Я как всегда пытался связать все это дело через контроллер, но почему-то onChange не видит value и значение туда не передается как я понял.
`<Controller 
      control={control}
      name="email"
      onChange={ (event) => setEmail(event.target.value) }
      rules={{
            required: true,
            minLength: 1,
            maxLength: {
                  value: 50,
                  message: "*Почта слишком большая",
            }
      }}
      render={({ field: {onChange, onBlur, value} }) =>
      <>
      <DadataSuggestions 
            token="token"
            onSelect={ (suggestion) => console.log(suggestion) }
            service="email"
            count={5}
            onBlur={onBlur}
            onChange={ (event) => onChange(event.target.value) } // проблема вся вот в этой строчке
/>
</>
}
/>
`

**Comment by HeisPovedim** [comment]
@nobbynobbs

**Comment by HeisPovedim** [comment]
В консоль выводится вот такая вот ошибка:
`Uncaught TypeError: Cannot read properties of undefined (reading 'value')`
Через некоторое время react падает.

**Comment by nobbynobbs** [comment]
привет! эту библиотеку не надо использовать, она не поддерживается, не развивается, а автор давно забыл реакт. снесу в архив чтобы людей не смущала.
