### ISSUE TITLE
Is it possible to set predefined value for text input?

### ISSUE THREAD

**Issue by indapublic** [nobbynobbs/react-dadata-suggestions#7]

**Comment by nobbynobbs** [comment]
Yes it's possible, just use prop `query`.
See first example on [codesandbox](https://codesandbox.io/s/p95804280q).

**Comment by indapublic** [comment]
It's very weird, because I already passed `query` to component and it doesn't contain any text

All versions are the same:

> "react-dadata-suggestions": "^0.4.6",
> "react-dom": "^16.2.0",
> "react": "^16.2.0",

**Comment by indapublic** [comment]
Ok, seems like component not rerender if query has been changed

**Comment by nobbynobbs** [comment]
I'm not sure I correctly understand the question.

In a nutshell. You can install default value for query and it will be rendered after component initialization, but after that you can't change query value programmatically.

**Comment by indapublic** [comment]
I'm using your component inside my component
Something like that.

```
render(){
return <div>
<ReactDadataSuggestions query={this.state.value}/>
</div>
}
```

So first value is '' for example and it's has been passed successfully. Then I change my state value to 'New York', but ReactDadataSuggestions input still have empty value inside DOM structure

**Comment by nobbynobbs** [comment]
Right, it doesn't work this way. Prop `query` it's just default value, component uses it just once during initialization.

**Comment by RocketSc** [comment]
#8

**Comment by nobbynobbs** [comment]
@indapublic update to version 0.4.7 please.

**Comment by indapublic** [comment]
So quick reaction! Cheers
